package scriptkit

import "strings"

var ScanInterlace = strings.Join([]string{
	`#!/bin/bash`,
	`#`,
	`set -o nounset    # error when referencing undefined variable`,
	`set -o errexit    # exit when command fails`,
	`shopt -s extglob`,
	`shopt -s nullglob`,
	`#`,
	`PRIORITY=1`,
	`#`,
	`#`,
	`# Определение переменных`,
	`PROJECT_DIRECTORY="|=directory=|"`,
	`FILE="|=file=|"`,
	`LOG_FILE="${PROJECT_DIRECTORY}/${FILE}.idet"`,
	`#`,
	`#`,
	`# Проверка существования исходного файла`,
	`if [ ! -f "${PROJECT_DIRECTORY}/${FILE}" ]; then`,
	`    echo "Ошибка: Файл ${PROJECT_DIRECTORY}/${FILE} не найден!" | tee "$LOG_FILE"`,
	`    exit 1`,
	`fi`,
	`#`,
	`#`,
	`# Выполнение проверки интерлейса`,
	`echo "Начинаем анализ интерлейса для файла: $FILE" `,
	`echo "Статистика будет сохранена в: $LOG_FILE" `,
	`echo "==================================================" `,
	`#`,
	`#`,
	`# Создаем временный файловый дескриптор`,
	`exec 3>&1`,
	`#`,
	`# Запускаем ffmpeg с разделением потоков`,
	`ffmpeg \`,
	`    -hide_banner \`,
	`    -i "${PROJECT_DIRECTORY}/${FILE}" \`,
	`    -vf "idet" \`,
	`    -an \`,
	`    -f rawvideo \`,
	`    -y /dev/null \`,
	`    1> >(grep --line-buffered -E 'frame=' | tee -a /dev/fd/3) \`,
	`    2> >(tee -a /dev/fd/3 | grep --line-buffered -E 'idet|Repeated Fields|Single frame detection|Multi frame detection' > "$LOG_FILE")`,
	`#`,
	`#`,
	`# Закрываем временный дескриптор`,
	`exec 3>&-`,
	`echo "=================================================="`,
	`echo "Анализ завершен. Результаты сохранены в $LOG_FILE" `,
	`mv "$0" /home/pemaltynov/IN/_DONE/bash/`,
}, "\n")

var Amedia1 = strings.Join([]string{
	`#!/bin/bash`,
	`#`,
	`set -o nounset    # error when referencing undefined variable`,
	`set -o errexit    # exit when command fails`,
	`shopt -s extglob`,
	`shopt -s nullglob`,
	`#`,
	`PRIORITY=6`,
	`#`,
	`#`,
	`# Определение переменных`,
	`SOURCE="|=source=|"`,
	`BASE_WITH_SEASON="|=base_with_season=|"`,
	`OUTBASE="|=outbase=|"`,
	`YADIF="|=yadif=|"`,
	`AUDIO_SUFFIX_1="|=suffix_1=|"`,
	`#`,
	`#Генерирование вторичных переменных`,
	`TARGET_DIR="/mnt/pemaltynov/ROOT/EDIT/_amedia/${BASE_WITH_SEASON}"`,
	`BUFFER="/home/pemaltynov/IN"`,
	`IN_PROGRESS="${BUFFER}/_IN_PROGRESS"`,
	`DONE="${BUFFER}/_DONE"`,
	`NOTIFICATIONS="${BUFFER}/notifications"`,
	`READY_FILE="${OUTBASE}.ready"`,
	``,
	`#`,
	`# Создаем пути`,
	`mkdir -p ${TARGET_DIR}`,
	`mv "${BUFFER}/${SOURCE}" "${IN_PROGRESS}/${SOURCE}"`,
	``,
	`#Сборка команды`,
	``,
	`fflite -n -r 25 -i "${IN_PROGRESS}/${SOURCE}" \`,
	`  -filter_complex "[0:v:0]${YADIF}setsar=(1/1)[vidHD];[0:a:0]aresample=48000,atempo=25/(25/1)[aud1]" \`,
	`  -map "[vidHD]" -c:v libx264 -preset medium -crf 21 -pix_fmt yuv420p -profile high -g 0 -map_metadata -1 -map_chapters -1 "${TARGET_DIR}/${OUTBASE}_HD.mp4" \`,
	`  -map "[aud1]" -c:a alac -compression_level 0 -map_metadata -1 -map_chapters -1 "${TARGET_DIR}/${OUTBASE}_HD_${AUDIO_SUFFIX_1}.m4a"`,
	`mv "${IN_PROGRESS}/${SOURCE}" "${DONE}/${SOURCE}"`,
	`touch "${TARGET_DIR}/${READY_FILE}" && printf ${TARGET_DIR}/${READY_FILE} >> ${TARGET_DIR}/${READY_FILE}`,
	`cp ${TARGET_DIR}/${OUTBASE}.ready ${NOTIFICATIONS}/${READY_FILE}`,
	`mv "$0" /home/pemaltynov/IN/_DONE/bash/`,
}, "\n")

var Amedia2 = strings.Join([]string{
	`#!/bin/bash`,
	`#`,
	`set -o nounset    # error when referencing undefined variable`,
	`set -o errexit    # exit when command fails`,
	`shopt -s extglob`,
	`shopt -s nullglob`,
	`#`,
	`PRIORITY=6`,
	`#`,
	`#`,
	`# Определение переменных`,
	`SOURCE="|=source=|"`,
	`BASE_WITH_SEASON="|=base_with_season=|"`,
	`OUTBASE="|=outbase=|"`,
	`YADIF="|=yadif=|"`,
	`AUDIO_SUFFIX_1="|=suffix_1=|"`,
	`AUDIO_SUFFIX_2="|=suffix_2=|"`,
	`#`,
	`#Генерирование вторичных переменных`,
	`TARGET_DIR="/mnt/pemaltynov/ROOT/EDIT/_amedia/${BASE_WITH_SEASON}"`,
	`BUFFER="/home/pemaltynov/IN"`,
	`IN_PROGRESS="${BUFFER}/_IN_PROGRESS"`,
	`DONE="${BUFFER}/_DONE"`,
	`NOTIFICATIONS="${BUFFER}/notifications"`,
	`READY_FILE="${OUTBASE}.ready"`,
	``,
	`#`,
	`# Создаем пути`,
	`mkdir -p ${TARGET_DIR}`,
	`mv "${BUFFER}/${SOURCE}" "${IN_PROGRESS}/${SOURCE}"`,
	``,
	`#Сборка команды`,
	``,
	`fflite -n -r 25 -i "${IN_PROGRESS}/${SOURCE}" \`,
	`  -filter_complex "[0:v:0]${YADIF}setsar=(1/1)[vidHD];[0:a:0]aresample=48000,atempo=25/(25/1)[aud1];[0:a:1]aresample=48000,atempo=25/(25/1)[aud2]" \`,
	`  -map "[vidHD]" -c:v libx264 -preset medium -crf 21 -pix_fmt yuv420p -profile high -g 0 -map_metadata -1 -map_chapters -1 "${TARGET_DIR}/${OUTBASE}_HD.mp4" \`,
	`  -map "[aud1]" -c:a alac -compression_level 0 -map_metadata -1 -map_chapters -1 "${TARGET_DIR}/${OUTBASE}_HD_${AUDIO_SUFFIX_1}.m4a" \`,
	`  -map "[aud2]" -c:a alac -compression_level 0 -map_metadata -1 -map_chapters -1 "${TARGET_DIR}/${OUTBASE}_HD_${AUDIO_SUFFIX_2}.m4a"`,
	`mv "${IN_PROGRESS}/${SOURCE}" "${DONE}/${SOURCE}"`,
	`touch "${TARGET_DIR}/${READY_FILE}" && printf ${TARGET_DIR}/${READY_FILE} >> ${TARGET_DIR}/${READY_FILE}`,
	`cp ${TARGET_DIR}/${OUTBASE}.ready ${NOTIFICATIONS}/${READY_FILE}`,
	`mv "$0" /home/pemaltynov/IN/_DONE/bash/`,
}, "\n")

var Amedia2S = strings.Join([]string{
	`#!/bin/bash`,
	`#`,
	`set -o nounset    # error when referencing undefined variable`,
	`set -o errexit    # exit when command fails`,
	`shopt -s extglob`,
	`shopt -s nullglob`,
	`#`,
	`PRIORITY=6`,
	`#`,
	`#`,
	`# Определение переменных`,
	`SOURCE="|=source=|"`,
	`SRT="|=srt=|"`,
	`BASE_WITH_SEASON="|=base_with_season=|"`,
	`OUTBASE="|=outbase=|"`,
	`YADIF="|=yadif=|"`,
	`AUDIO_SUFFIX_1="|=suffix_1=|"`,
	`AUDIO_SUFFIX_2="|=suffix_2=|"`,
	`#`,
	`#Генерирование вторичных переменных`,
	`TARGET_DIR="/mnt/pemaltynov/ROOT/EDIT/_amedia/${BASE_WITH_SEASON}"`,
	`BUFFER="/home/pemaltynov/IN"`,
	`IN_PROGRESS="${BUFFER}/_IN_PROGRESS"`,
	`DONE="${BUFFER}/_DONE"`,
	`NOTIFICATIONS="${BUFFER}/notifications"`,
	`READY_FILE="${OUTBASE}.ready"`,
	``,
	`#`,
	`# Создаем пути`,
	`mkdir -p ${TARGET_DIR}`,
	`mv "${BUFFER}/${SOURCE}" "${IN_PROGRESS}/${SOURCE}"`,
	`mv "${BUFFER}/${SRT}" "${IN_PROGRESS}/${SRT}"`,
	``,
	`#Сборка команды`,
	``,
	`fflite -n -r 25 -i "${IN_PROGRESS}/${SOURCE}" \`,
	`  -filter_complex "[0:v:0]${YADIF}setsar=(1/1)[vidHD];[0:a:0]aresample=48000,atempo=25/(25/1)[aud1];[0:a:1]aresample=48000,atempo=25/(25/1)[aud2]" \`,
	`  -map "[vidHD]" -c:v libx264 -preset medium -crf 21 -pix_fmt yuv420p -profile high -g 0 -map_metadata -1 -map_chapters -1 "${TARGET_DIR}/${OUTBASE}_HD.mp4" \`,
	`  -map "[aud1]" -c:a alac -compression_level 0 -map_metadata -1 -map_chapters -1 "${TARGET_DIR}/${OUTBASE}_HD_${AUDIO_SUFFIX_1}.m4a" \`,
	`  -map "[aud2]" -c:a alac -compression_level 0 -map_metadata -1 -map_chapters -1 "${TARGET_DIR}/${OUTBASE}_HD_${AUDIO_SUFFIX_2}.m4a"`,
	`cp "${IN_PROGRESS}/${SRT}" "${TARGET_DIR}/${OUTBASE}.srt"`,
	`mv "${IN_PROGRESS}/${SOURCE}" "${DONE}/${SOURCE}"`,
	`mv "${IN_PROGRESS}/${SRT}" "${DONE}/${SRT}"`,
	`touch "${TARGET_DIR}/${READY_FILE}" && printf ${TARGET_DIR}/${READY_FILE} >> ${TARGET_DIR}/${READY_FILE}`,
	`cp ${TARGET_DIR}/${OUTBASE}.ready ${NOTIFICATIONS}/${READY_FILE}`,
	`mv "$0" /home/pemaltynov/IN/_DONE/bash/`,
}, "\n")
