package scriptkit

import "strings"

var ScanInterlace = strings.Join([]string{
	`#!/bin/bash`,
	`#`,
	`set -o nounset    # error when referencing undefined variable`,
	`set -o errexit    # exit when command fails`,
	`shopt -s extglob`,
	`shopt -s nullglob`,
	`#`,
	`PRIORITY=1`,
	`#`,
	`#`,
	`# Определение переменных`,
	`PROJECT_DIRECTORY="|=directory=|"`,
	`FILE="|=file=|"`,
	`LOG_FILE="${PROJECT_DIRECTORY}/${FILE}.idet"`,
	`#`,
	`#`,
	`# Проверка существования исходного файла`,
	`if [ ! -f "${PROJECT_DIRECTORY}/${FILE}" ]; then`,
	`    echo "Ошибка: Файл ${PROJECT_DIRECTORY}/${FILE} не найден!" | tee "$LOG_FILE"`,
	`    exit 1`,
	`fi`,
	`#`,
	`#`,
	`# Выполнение проверки интерлейса`,
	`echo "Начинаем анализ интерлейса для файла: $FILE" `,
	`echo "Статистика будет сохранена в: $LOG_FILE" `,
	`echo "==================================================" `,
	`#`,
	`#`,
	`# Создаем временный файловый дескриптор`,
	`exec 3>&1`,
	`#`,
	`# Запускаем ffmpeg с разделением потоков`,
	`ffmpeg \`,
	`    -hide_banner \`,
	`    -i "${PROJECT_DIRECTORY}/${FILE}" \`,
	`    -vf "idet" \`,
	`    -an \`,
	`    -f rawvideo \`,
	`    -y /dev/null \`,
	`    1> >(grep --line-buffered -E 'frame=' | tee -a /dev/fd/3) \`,
	`    2> >(tee -a /dev/fd/3 | grep --line-buffered -E 'idet|Repeated Fields|Single frame detection|Multi frame detection' > "$LOG_FILE")`,
	`#`,
	`#`,
	`# Закрываем временный дескриптор`,
	`exec 3>&-`,
	`echo "=================================================="`,
	`echo "Анализ завершен. Результаты сохранены в $LOG_FILE" `,
	`mv "$0" /home/pemaltynov/IN/_DONE/bash/`,
}, "\n")
